// ============================================================
// Myanmar79 · 霓虹财富 —— 界面语言文件：EN
// 本文件仅管理界面文字内容，不包含任何游戏逻辑
// 由 index.html 在 main.js 之前加载，供 main.js 中的 i18n 系统读取
// ============================================================

window.LANG_EN = window.LANG_EN || {};

// ---- 表C：主 translations 使用的完整界面文案（原 const translations['en'] 的内容） ----
window.LANG_EN.translations = {
                    draw: 'DRAW',
                    prizeResultPrefix: '🎉 You won ',
                    prizeResultSuffix: '！',
                    congratsTitle: 'Congratulations! Bonus Awarded!',
                    bonusDeposited: 'Bonus automatically credited to your account',
                    thanksParticipating: 'Thanks for participating!',
                    goodLuckNext: 'Better luck next time',
                    step1_claim: 'Claim Now',
                    step2_title: 'Bonus Ready',
                    step2_sub: 'Exclusive for new players',
                    reg_username_ph: 'Username',
                    reg_phone_ph: 'Phone Number',
                    reg_pwd_ph: 'Password',
                    reg_confirm_pwd_ph: 'Confirm password',
                    reg_captcha_ph: 'Enter verification code',
                    protocol_label: 'I have read and agree to "',
                    protocol_mid: '" and "',
                    protocol_end: '',
                    userAgreement: 'User Agreement',
                    privacyPolicy: 'Privacy Policy',
                    step2_submit: 'Register & Claim',
                    switch_login: 'Already a member?',
                    switch_login_span: 'Log in',
                    step3_title: 'Welcome back',
                    login_phone_or_id_ph: 'Phone / Account ID',
                    login_pwd_ph: 'Password',
                    risk_tips: '🟣 Friendly Reminder: After successful login, recharge in the bonus popup to get doubled rewards',
                    step3_submit: 'Log in',
                    switch_register: 'No account?',
                    switch_register_span: 'Go register for welcome package',
                    protocol_required: 'Please check the agreement box first.',
                    register_success: '🎉 Registration successful! Bonus ',
                    login_msg: '🔑 Login successful.',
                    noBonus: 'No registration bonus claimed',
                    confirm: 'Confirm',
                    langMy: 'Myanmar',
                    langEn: 'English',
                    langZh: '简体中文',
                    freeChancesLeft: 'Free tries left: {count}',
                    chancesUsed: '{count} chances used up, activate to claim',
                    gameOverTitle: 'Draw complete — your highest prize is reserved!',
                    gameOverSub: 'The system has saved the highest prize from your three draws. You won\'t lose any earned rewards.',
                    gameOverClaim: 'Activate now to lock in your prize',
                    wheelSectorLabels: ['Standard', 'Lucky Prize', 'Mystery Prize', 'Premium Prize', 'Special Prize', 'Luxury Prize', 'Rare Prize', 'Supreme Prize', 'Super Jackpot', 'Grand Jackpot'],
                    inspireMessages: ['✨', 'Keep spinning', 'Good luck', 'Open the gift'],
                    pwd_length_error: 'Password must be exactly 6 characters',
                    pwd_max_length_error: 'Password cannot exceed 6 characters',
                    pwd_format_error: 'Password must contain both letters and numbers',
                    pwd_mismatch: 'Passwords do not match',
                    captcha_error: 'Incorrect verification code',
                    captcha_expired: 'Verification code expired, please refresh',
                    captcha_not_generated: 'Please generate a code first',
                    captcha_already_used: 'Code already used, please refresh',
                    captcha_valid: 'Valid',
                    prizeHistoryLabel: 'Draw #{round}',
                    prizeHistoryHint: '← Swipe to view →',
                    slot2_marketing: '🎯 Spin again for bigger prizes!',
                    slot3_marketing: '🌟 Last chance, the jackpot is waiting!',
                    phone_error_format: 'Please enter a valid phone number.',
                    phone_error_registered: 'This phone number is already registered. Please log in.',
                    username_error_empty: 'Username cannot be empty.',
                    username_error_exists: 'Username already exists. Please try another.',
                    username_error_invalid: 'Username only supports letters and numbers.',
                    login_pwd_format_error: 'Password format error, please re-enter.',
                    login_error_account_or_pwd: 'Invalid account or password, please re-enter.',
                    login_error_too_many_attempts: 'Too many failed attempts, please try again in {minutes} minutes.',
                    login_forgot_pwd: 'Forgot password?',
                    login_forgot_pwd_title: 'Contact Support',
                    login_forgot_pwd_body: 'Please contact our support team to reset your password.',
                    login_forgot_pwd_contact: 'support@myanmar79.com',
                    login_bonus_title: "Today's Exclusive Check-in Bonus",
                    login_bonus_sub: '🟣 Limited Time Login Bonus',
                    login_bonus_badge: '06:00',
                    login_bonus_desc: 'Complete login within 6 minutes to activate check-in bonus, 7-day check-in for extra rewards',
                    recharge_title: '🎁 Today\'s Recharge Bonus',
                    recharge_activity: '🟣 Limited Time Recharge Reward',
                    recharge_desc: 'After successful login, recharge in the bonus popup to get doubled rewards',
                    recharge_btn: 'Recharge Now',
                    forgot_close: 'Close',
                    placeholder_title: 'Myanmar79 Game Hall',
                    placeholder_sub: 'Welcome to Myanmar79',
                    placeholder_hint: 'Game page under construction, stay tuned…',
                    placeholder_btn: 'Back',
                    bonus_timer_expired: 'Expired',
                    bonus_desc_expired: 'Sorry, the limited-time double bonus has ended. Log in to activate the regular check-in package.',
                    coinTotalLabel: 'TOTAL WIN',
                    launch_connecting: 'Connecting...',
                    launch_loading: 'Loading...',
                    launch_waiting: 'Connecting, please wait...',
                    launch_slow_network: 'Slow network, connecting...',
                    launch_offline_title: 'No Internet Connection',
                    launch_offline_desc: 'Please check your network and try again',
                    launch_timeout_title: 'Connection Timeout',
                    launch_timeout_desc: 'Connection timed out, please retry',
                    launch_error_title: 'Connection Failed',
                    launch_error_desc: 'Connection failed, please try again later',
                    launch_retry: 'Retry',
                    launch_reconnect: 'Reconnect',
                    network_disconnected: 'Network disconnected',
                    network_recovered: 'Network recovered',
                    pwa_install_banner_desc: 'Install to desktop for faster launch',
                    pwa_install_btn: 'Install',
                    pwa_ios_guide_text: 'Tap Share → Add to Home Screen',
                    langBtnLabel: 'Language',
                    wheelMainText: 'DRAW',
                    wheelSubText: '2 tries left',
                    feature_in_dev: 'Feature in development',
                    gotIt: 'Got it',
                    themeDay: 'Day',
                    themeNight: 'Night',
                    brandSlogan: 'The entertainment platform chosen by 200,000 players across Myanmar',
                    promoScroll1: 'First Deposit, Double Bonus',
                    promoScroll2: 'Register & Get Bonus',
                    promoScroll3: 'Instant Withdrawal',
                    promoScroll4: 'Instant Top-up',
                    brightness1Label: 'Soft',
                    brightness1Desc: 'Best for a completely dark room',
                    brightness2Label: 'Comfort',
                    brightness2Desc: 'Best with dim lighting',
                    brightness3Label: 'Bright',
                    brightness3Desc: 'Best with bedside lamp on',
                    homeLoginMain: 'Log in',
                    homeLoginSub: 'Already have an account? Log in now',
                    homeRegisterMain: 'Sign up',
                    homeRegisterSub: 'New user? Sign up now',
                    streamTagChars: ['Live', 'Data', 'Stream'],
                    ticker1: 'Real data, live synced!',
                    ticker2: '🎁 New player bonus, limited time!',
                    ticker3: '🎉 Daily check-in, endless rewards!',
                    ticker4: '🔥 Lucky wheel, spinning now!',
                    ticker5: '💰 Fast withdrawal, guaranteed!',
                    ticker6: '✨ Great perks, always on!',
                    streamPrizeLabel: 'Prize',
                    streamAction1: 'won',
                    streamAction2: 'hit',
                    streamAction3: 'won',
                    streamTimeJustNow: 'just now',
                    streamTimeSecondsAgo: '{n} sec ago',
                    streamTimeMinutesAgo: '{n} min ago',
                    streamTimeHoursAgo: '{n} hr ago',
                    csFloatLabel: 'Support',
                    appDownloadText: 'Download App'
                };

// ---- 表A：setLanguage() 网络错误提示精简文案（原 var texts.en 的内容） ----
window.LANG_EN.networkText = { title: 'No Internet Connection', desc: 'Connection failed, please check your network', retry: 'Retry' };

// ---- 表B：getText() 启动页精简翻译表（原 var T.en 的内容） ----
window.LANG_EN.launchText = {
                        launch_connecting: 'Connecting...',
                        launch_loading: 'Loading...',
                        launch_waiting: 'Connecting, please wait...',
                        launch_slow_network: 'Slow network, connecting...',
                        launch_offline_title: 'No Internet Connection',
                        launch_offline_desc: 'Please check your network and try again',
                        launch_timeout_title: 'Connection Timeout',
                        launch_timeout_desc: 'Connection timed out, please retry',
                        launch_error_title: 'Connection Failed',
                        launch_error_desc: 'Connection failed, please try again later',
                        launch_retry: 'Retry',
                        launch_reconnect: 'Reconnect',
                        network_disconnected: 'Network disconnected',
                        network_recovered: 'Network recovered',
                        pwa_install_banner_desc: 'Install to desktop for faster launch',
                        pwa_install_btn: 'Install',
                        pwa_ios_guide_text: 'Tap Share → Add to Home Screen'
                    };

// ---- 用户协议 / 隐私政策富文本（原 const userAgreementEN / privacyPolicyEN） ----
window.LANG_EN.userAgreement = `<p><strong>User Agreement</strong></p><p><strong>Last Updated: May 15, 2026</strong></p><p>Welcome to the Myanmar79 Gaming Platform ("the Platform"). Please read the following terms carefully before registering and using our services. By checking the agreement box and registering, you confirm that you fully understand and agree to all terms of this Agreement.</p><p><strong>1. Service Description</strong></p><p>1.1 The Platform provides online entertainment gaming services, available only to users aged 18 and above.</p><p>1.2 Users must ensure that the laws and regulations of their country or region permit the use of the Platform's services.</p><p>1.3 The Platform reserves the right to modify, suspend, or terminate services at any time without prior notice.</p><p><strong>2. Account Management</strong></p><p>2.1 Users must provide true and accurate personal information during registration and are responsible for its authenticity.</p><p>2.2 Each user is limited to one account. Multiple accounts and account transfers are strictly prohibited.</p><p>2.3 Users shall safeguard their account passwords. Losses resulting from password disclosure shall be borne by the user.</p><p><strong>3. Game Rules</strong></p><p>3.1 Users shall comply with all game rules established by the Platform when participating in games.</p><p>3.2 Any form of cheating is strictly prohibited. Upon discovery, the account will be immediately frozen.</p><p>3.3 Game rewards and bonuses shall be distributed based on the Platform's system records.</p><p><strong>4. Disclaimer</strong></p><p>4.1 The Platform is not liable for service interruptions caused by network failures, system maintenance, or other force majeure events.</p><p>4.2 The Platform is not responsible for any indirect losses incurred by users through the use of its services.</p><p><strong>5. Agreement Modifications</strong></p><p>5.1 The Platform may modify the terms of this Agreement at any time. The modified Agreement shall take effect upon publication.</p><p>5.2 Continued use of the Platform's services constitutes acceptance of the modified Agreement.</p><p>For any inquiries, please contact: support@myanmar79.com</p>`;
window.LANG_EN.privacyPolicy = `<p><strong>Privacy Policy</strong></p><p><strong>Last Updated: May 15, 2026</strong></p><p>Myanmar79 Gaming Platform ("we" or "us") places great importance on protecting user privacy. This Privacy Policy explains how we collect, use, and safeguard your personal information.</p><p><strong>1. Information Collection</strong></p><p>1.1 Registration Information: When you register an account, we collect basic information such as your name, phone number, and email address.</p><p>1.2 Device Information: We collect your device model, operating system version, and IP address for security verification purposes.</p><p>1.3 Game Data: Your game records, top-up history, and reward records are securely stored.</p><p><strong>2. Information Usage</strong></p><p>2.1 We use your information to provide, maintain, and improve our platform services.</p><p>2.2 We may use your contact information to send important notifications and promotional messages.</p><p>2.3 We will never sell your personal information to any third party.</p><p><strong>3. Information Protection</strong></p><p>3.1 We employ industry-standard security measures including SSL encryption and firewalls to protect your data.</p><p>3.2 All payment information is transmitted through encrypted channels to ensure transaction security.</p><p><strong>4. Cookie Usage</strong></p><p>4.1 We use cookie technology to enhance user experience. You may disable cookies in your browser settings.</p><p><strong>5. User Rights</strong></p><p>5.1 You have the right to access, correct, or delete your personal information at any time.</p><p>5.2 To exercise these rights, please contact: support@myanmar79.com</p><p><strong>6. Policy Updates</strong></p><p>6.1 We may update this Privacy Policy from time to time. Updates will be announced through platform notifications.</p><p>Thank you for trusting Myanmar79!</p>`;
