// ============================================================
// Myanmar79 · 霓虹财富 —— 界面语言文件：ZH
// 本文件仅管理界面文字内容，不包含任何游戏逻辑
// 由 index.html 在 main.js 之前加载，供 main.js 中的 i18n 系统读取
// ============================================================

window.LANG_ZH = window.LANG_ZH || {};

// ---- 表C：主 translations 使用的完整界面文案（原 const translations['zh'] 的内容） ----
window.LANG_ZH.translations = {
                    draw: '免费抽奖',
                    prizeResultPrefix: '🎉 恭喜获得 ',
                    prizeResultSuffix: '！',
                    congratsTitle: '恭喜获得注册奖金！',
                    bonusDeposited: '注册账号即可存入账户提现',
                    thanksParticipating: '谢谢参与！',
                    goodLuckNext: '下次好运等着您',
                    step1_claim: '激活奖金',
                    step2_title: '最高奖金已就绪',
                    step2_sub: '新玩家专享福利，注册即领！',
                    reg_username_ph: '用户名',
                    reg_phone_ph: '手机号',
                    reg_pwd_ph: '密码',
                    reg_confirm_pwd_ph: '确认密码',
                    reg_captcha_ph: '请输入验证码',
                    protocol_label: '我已阅读并同意《',
                    protocol_mid: '》与《',
                    protocol_end: '》',
                    userAgreement: '用户协议',
                    privacyPolicy: '隐私政策',
                    step2_submit: '立即注册领奖',
                    switch_login: '已有账号？',
                    switch_login_span: '立即登录',
                    step3_title: '欢迎回来',
                    login_phone_or_id_ph: '手机号 / 账号ID',
                    login_pwd_ph: '密码',
                    risk_tips: '🟣 温馨提示：登录成功后，在福利弹窗内充值即可获得翻倍奖金',
                    step3_submit: '登录',
                    switch_register: '没有账号？',
                    switch_register_span: '去注册领取新人礼包',
                    protocol_required: '请先勾选同意用户协议',
                    register_success: '🎉 注册成功！奖励 ',
                    login_msg: '🔑 登录成功！',
                    noBonus: '未领取注册奖金',
                    confirm: '确认',
                    langMy: 'Myanmar',
                    langEn: 'English',
                    langZh: '简体中文',
                    freeChancesLeft: '免费抽奖机会：剩余 {count} 次',
                    chancesUsed: '免费抽奖机会已全部使用，请立即激活奖金。',
                    gameOverTitle: '抽奖结束，最高奖金为您保留！',
                    gameOverSub: '系统已为您保留三次中的最高奖金，您不会损失任何已得奖励。',
                    gameOverClaim: '立即激活，锁定奖金',
                    wheelSectorLabels: ['普通奖励', '幸运奖励', '神秘奖励', '高级奖励', '特别奖励', '豪华奖励', '稀有奖励', '至尊奖励', '超级大奖', '终极大奖'],
                    inspireMessages: ['✨', '继续旋转', '祝您好运', '打开礼物吧'],
                    pwd_length_error: '密码长度必须为6位',
                    pwd_max_length_error: '密码最长是6位数',
                    pwd_format_error: '密码必须包含字母和数字',
                    pwd_mismatch: '两次密码输入不一致',
                    captcha_error: '验证码错误，请重新输入',
                    captcha_expired: '验证码已过期，请刷新重试',
                    captcha_not_generated: '请先生成验证码',
                    captcha_already_used: '验证码已使用，请刷新',
                    captcha_valid: '验证通过',
                    prizeHistoryLabel: '第{round}次抽奖',
                    prizeHistoryHint: '← 左右滑动查看 →',
                    slot2_marketing: '再抽一次，冲击更高奖金！',
                    slot3_marketing: '最后一次机会，冲击最高奖金！',
                    phone_error_format: '请输入正确的手机号。',
                    phone_error_registered: '该手机号已注册，请直接登录。',
                    username_error_empty: '用户名不能为空。',
                    username_error_exists: '用户名已存在，请重新设置。',
                    username_error_invalid: '用户名仅支持英文字母和数字。',
                    login_pwd_format_error: '密码格式错误，请重新输入。',
                    login_error_account_or_pwd: '账号或密码错误，请重新输入。',
                    login_error_too_many_attempts: '密码错误次数过多，请 {minutes} 分钟后再尝试。',
                    login_forgot_pwd: '忘记密码？',
                    login_forgot_pwd_title: '联系客服',
                    login_forgot_pwd_body: '请联系我们的客服团队协助您找回密码。',
                    login_forgot_pwd_contact: 'support@myanmar79.com',
                    login_bonus_title: '今日专属签到福利',
                    login_bonus_sub: '🟣 限时登录奖励',
                    login_bonus_badge: '06:00',
                    login_bonus_desc: '6分钟内完成登录，激活签到福利，7天签到领取额外奖金',
                    recharge_title: '🎁 今日充值福利',
                    recharge_activity: '🟣 限时充值奖励开启',
                    recharge_desc: '登录成功后，在福利弹窗内充值即可获得翻倍奖金',
                    recharge_btn: '立即充值',
                    forgot_close: '关闭',
                    placeholder_title: 'Myanmar79 游戏大厅',
                    placeholder_sub: '欢迎来到 Myanmar79',
                    placeholder_hint: '游戏主页面正在建设中，敬请期待…',
                    placeholder_btn: '返回',
                    bonus_timer_expired: '已失效',
                    bonus_desc_expired: '非常遗憾 限时翻倍已结束，登录仍可激活常规签到礼包',
                    coinTotalLabel: '累计奖金',
                    launch_connecting: '正在连接...',
                    launch_loading: '正在加载...',
                    launch_waiting: '正在连接，请稍候...',
                    launch_slow_network: '网络较慢，正在连接...',
                    launch_offline_title: '没有网络连接',
                    launch_offline_desc: '请检查网络连接后重试',
                    launch_timeout_title: '连接超时',
                    launch_timeout_desc: '连接超时，请重试',
                    launch_error_title: '连接失败',
                    launch_error_desc: '连接失败，请稍后再试',
                    launch_retry: '重试',
                    launch_reconnect: '重新连接',
                    network_disconnected: '网络连接已断开',
                    network_recovered: '网络已恢复',
                    pwa_install_banner_desc: '安装到桌面，获得更快启动体验',
                    pwa_install_btn: '安装',
                    pwa_ios_guide_text: '点击分享按钮 → 添加到主屏幕',
                    langBtnLabel: '语言',
                    wheelMainText: '抽奖',
                    wheelSubText: '还剩下2次',
                    feature_in_dev: '功能开发中',
                    gotIt: '知道了',
                    themeDay: '日间',
                    themeNight: '夜间',
                    brandSlogan: '全缅20万玩家共同选择的娱乐平台',
                    promoScroll1: '首充翻倍送',
                    promoScroll2: '注册送奖金',
                    promoScroll3: '提现秒到账',
                    promoScroll4: '充值秒到账',
                    brightness1Label: '柔和',
                    brightness1Desc: '适合全黑房间',
                    brightness2Label: '舒适',
                    brightness2Desc: '适合有微弱灯光',
                    brightness3Label: '明亮',
                    brightness3Desc: '适合床头灯亮着',
                    homeLoginMain: '登录',
                    homeLoginSub: '已有账号? 立即登录',
                    homeRegisterMain: '注册',
                    homeRegisterSub: '新用户? 快速注册',
                    streamTagChars: ['动态', '数据', '流'],
                    ticker1: '真实数据，实时同步！',
                    ticker2: '🎁 新人福利，限时开启！',
                    ticker3: '🎉 每日签到，奖励不断！',
                    ticker4: '🔥 幸运大转盘，火热开启！',
                    ticker5: '💰 极速提现，稳定到账！',
                    ticker6: '✨ 精彩福利，持续放送！',
                    streamPrizeLabel: '奖金',
                    streamAction1: '恭喜获得',
                    streamAction2: '恭喜抽中',
                    streamAction3: '恭喜赢得',
                    streamTimeJustNow: '刚刚',
                    streamTimeSecondsAgo: '{n}秒前',
                    streamTimeMinutesAgo: '{n}分钟前',
                    streamTimeHoursAgo: '{n}小时前',
                    csFloatLabel: '客服',
                    appDownloadText: 'App下载'
                };

// ---- 表A：setLanguage() 网络错误提示精简文案（原 var texts.zh 的内容） ----
window.LANG_ZH.networkText = { title: '没有网络连接', desc: '连接失败，请检查你的网络设置', retry: '重试' };

// ---- 表B：getText() 启动页精简翻译表（原 var T.zh 的内容） ----
window.LANG_ZH.launchText = {
                        launch_connecting: '正在连接...',
                        launch_loading: '正在加载...',
                        launch_waiting: '正在连接，请稍候...',
                        launch_slow_network: '网络较慢，正在连接...',
                        launch_offline_title: '没有网络连接',
                        launch_offline_desc: '请检查网络连接后重试',
                        launch_timeout_title: '连接超时',
                        launch_timeout_desc: '连接超时，请重试',
                        launch_error_title: '连接失败',
                        launch_error_desc: '连接失败，请稍后再试',
                        launch_retry: '重试',
                        launch_reconnect: '重新连接',
                        network_disconnected: '网络连接已断开',
                        network_recovered: '网络已恢复',
                        pwa_install_banner_desc: '安装到桌面，获得更快启动体验',
                        pwa_install_btn: '安装',
                        pwa_ios_guide_text: '点击分享按钮 → 添加到主屏幕'
                    };

// ---- 用户协议 / 隐私政策富文本（原 const userAgreementZH / privacyPolicyZH） ----
window.LANG_ZH.userAgreement = `<p><strong>用户协议</strong></p><p><strong>最后更新日期：2026年5月15日</strong></p><p>欢迎使用 Myanmar79 游戏平台（以下简称"本平台"）。在注册和使用本平台服务前，请您仔细阅读以下条款。一旦您勾选同意并注册，即表示您已充分理解并同意本协议的全部内容。</p><p><strong>一、服务说明</strong></p><p>1.1 本平台提供在线娱乐游戏服务，仅供年满18周岁的用户使用。</p><p>1.2 用户需自行确保其所在国家或地区的法律法规允许使用本平台服务。</p><p>1.3 本平台保留随时修改、暂停或终止服务的权利，无需提前通知。</p><p><strong>二、账户管理</strong></p><p>2.1 用户注册时须提供真实、准确的个人信息，并对信息的真实性负责。</p><p>2.2 每个用户仅限注册一个账户，禁止多账户注册或账户转让。</p><p>2.3 用户应妥善保管账户密码，因密码泄露导致的损失由用户自行承担。</p><p><strong>三、游戏规则</strong></p><p>3.1 用户参与游戏时应遵守本平台制定的各项游戏规则。</p><p>3.2 本平台严禁任何形式的作弊行为，一经发现将立即冻结账户。</p><p>3.3 游戏奖励和奖金的发放以本平台系统记录为准。</p><p><strong>四、免责声明</strong></p><p>4.1 本平台对因网络故障、系统维护等原因造成的服务中断不承担责任。</p><p>4.2 本平台不对用户因使用服务而产生的任何间接损失负责。</p><p><strong>五、协议变更</strong></p><p>5.1 本平台有权随时修改本协议条款，修改后的协议一经发布即生效。</p><p>5.2 用户继续使用本平台服务即视为同意修改后的协议。</p><p>如有任何疑问，请联系客服：support@myanmar79.com</p>`;
window.LANG_ZH.privacyPolicy = `<p><strong>隐私政策</strong></p><p><strong>最后更新日期：2026年5月15日</strong></p><p>Myanmar79 游戏平台（以下简称"我们"）高度重视用户的隐私保护。本隐私政策旨在向您说明我们如何收集、使用和保护您的个人信息。</p><p><strong>一、信息收集</strong></p><p>1.1 注册信息：当您注册账户时，我们会收集您的姓名、手机号码、电子邮箱等基本信息。</p><p>1.2 设备信息：我们会收集您的设备型号、操作系统版本、IP地址等用于安全验证。</p><p>1.3 游戏数据：您的游戏记录、充值记录、奖励记录等将被安全存储。</p><p><strong>二、信息使用</strong></p><p>2.1 我们使用您的信息来提供、维护和改进平台服务。</p><p>2.2 我们可能使用您的联系方式向您发送重要通知和活动信息。</p><p>2.3 我们不会将您的个人信息出售给任何第三方。</p><p><strong>三、信息保护</strong></p><p>3.1 我们采用SSL加密、防火墙等业界标准安全措施保护您的数据。</p><p>3.2 所有支付信息均通过加密通道传输，确保交易安全。</p><p><strong>四、Cookie使用</strong></p><p>4.1 我们使用Cookie技术优化用户体验，您可在浏览器设置中禁用Cookie。</p><p><strong>五、用户权利</strong></p><p>5.1 您有权随时查询、更正或删除您的个人信息。</p><p>5.2 如需行使上述权利，请联系客服：support@myanmar79.com</p><p><strong>六、政策更新</strong></p><p>6.1 我们可能会不定期更新本隐私政策，更新后将通过平台公告通知。</p><p>感谢您信任 Myanmar79！</p>`;
